### PR TITLE
A bit of cleanup.  Maybe liked, maybe be hated.

### PR DESCRIPTION
**Pull request by rmcgirr83**
For your consideration

### CODE REVIEW

**Comment by rmcgirr83** [comment]
Travis sure is finicky.

**Comment by tas2580** [comment]
Most thinks I like, thank you :+1: 

But with the routing: do you think it's a good idea to use  username/password/email? I think there could be conflicts with other extensions.
I think it's better to use /extension/mode for URLs.

**Comment by rmcgirr83** [comment]
Those paths are specific to your namespace and I was just messing around within as I thought `regcheck/?username=username` looked sort of odd.  Completely up to you

**Comment by tas2580** [comment]
I changed the URLs back, it's not really beautiful but I think to keep them in namespace /regcheck/ would be better. Also this are AJAX URLs, so no normal user will see them.

**Comment by rmcgirr83** [comment]
Fair enough it is your extension after all. :smile:

**Pull request merged**
